name: CI for Multi-Module Spring Boot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Specify your Java version here

    - name: Verify Maven Wrapper
      run: |
        if [ ! -f mvnw ]; then
          echo "Maven wrapper not found, please add the Maven wrapper to your repository."
          exit 1
        fi

    - name: Build and test with Maven
      run: ./mvnw clean install --batch-mode

    - name: Run integration tests (if applicable)
      run: ./mvnw verify --batch-mode

    - name: List files for debugging
      run: ls -al

    - name: Display Maven output
      run: tail -n 50 ~/.m2/repository/maven-metadata.xml || echo "No Maven metadata file found."

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          target/*.jar
          target/*.war
