name: Build Multi-Module Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print working directory
      run: pwd

    - name: List directory contents
      run: ls -al

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Navigate to project directory
      run: |
        if [ -f "pom.xml" ]; then
          echo "Found pom.xml in the root directory."
        else
          echo "pom.xml not found in the root directory. Listing all directories..."
          ls -al
        fi

    - name: Build with Maven
      run: |
        if [ -f "pom.xml" ]; then
          mvn clean install --batch-mode
        else
          echo "pom.xml not found. Please check the directory structure."
          exit 1
        fi
